[package]
name = "poker-plonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poker-core = { workspace = true }
zplonk = { workspace = true }
zshuffle = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-bn254 = { workspace = true }
num-bigint = "0.4.3"
num-integer = "0.1.45"
rand_chacha =  "0.3"