[package]
name = "poker-plonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poker-core = { path = "../core", default-features = false }
zplonk = { path = "../../uzkge/zplonk"}
zshuffle = { path = "../../uzkge/shuffle"}
ark-ec = "0.4"
ark-ff = "0.4"
ark-ed-on-bn254 = "0.4"
ark-bn254 = "0.4"
num-bigint = "0.4.3"
num-integer = "0.1.45"