[package]
name = "poker-host"
version = "0.1.0"
edition = "2021"

[dependencies]
poker-methods = { path = "../methods" }
poker-core = { path = "../core", features= ["serialize0"] }
risc0-zkvm = { version = "0.20.1", features = ["prove"] }