[package]
name = "poker-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poker-core = { workspace = true }
poker-bonsai = { workspace = true }
poker-gadgets = { workspace = true }
z4-engine = { path = "../../z4/engine"}
tokio = "1.35"
async-trait = "0.1"
dotenv = "0.15"
serde_json = '1.0'
rand = "0.8"
rand_chacha = "0.3"