[package]
name = "poker-host"
version = "0.1.0"
edition = "2021"

[dependencies]
poker-methods.workspace = true
poker-core = { workspace = true, features= ["serialize0"] }
risc0-zkvm = { workspace = true, features = ["prove"] }